# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(010000)
$foreground = rgb(ECECE9)
$color0 = rgb(010000)
$color1 = rgb(71736F)
$color2 = rgb(906B67)
$color3 = rgb(757974)
$color4 = rgb(858982)
$color5 = rgb(8F908A)
$color6 = rgb(969791)
$color7 = rgb(DBDCD8)
$color8 = rgb(999A97)
$color9 = rgb(969994)
$color10 = rgb(C08F8A)
$color11 = rgb(9CA19B)
$color12 = rgb(B1B7AD)
$color13 = rgb(BEC1B8)
$color14 = rgb(C8CAC1)
$color15 = rgb(DBDCD8)
