[diego]
type = drive
client_id = 306784673870-qe2ond3ov2gqvv5gvucft6lj6fg4qcjv.apps.googleusercontent.com
client_secret = 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
scope = drive
token = {"access_token":"ya29.a0Aa7pCA8JqutRg2P6-9GjXQSKKfXN_3npc-SlJyZSJjuAPV3Pf8ZtuAlpMvPsDHhk5BXsRyRlPHW5DtTcKJoZyuZpFK59xoExid9q43VV77Mkq6-7wliwVIvQG46jbSz4FEKow8xaqRe8JSd7hk4r6o2j4oRbJzFshD0S9ayK5HWVuzth1OYCLXgASNNaaXebvS3yFKyvaCgYKATcSARQSFQHGX2MiBDKhI5SwagSwRGqdtbZ0hA0207","token_type":"Bearer","refresh_token":"1//0hByrSOWGioxKCgYIARAAGBESNwF-L9IrqJ4V3FEb3uENabkf4IhqtmYCgcPA7f1sFStHviAeY7akZ6qNxWcOZfHMi-RlQo4LWgU","expiry":"2025-12-11T12:03:19.774520988-05:00","expires_in":3599}
team_drive = 

