# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E2E1E1
background         #556B47
cursor             #8D7570

active_tab_foreground     #556B47
active_tab_background     #E2E1E1
inactive_tab_foreground   #E2E1E1
inactive_tab_background   #556B47

active_border_color   #E2E1E1
inactive_border_color #556B47
bell_border_color     #969791

color0      #EFEEED
color1		#969791
color2		#8F908A
color3		#858982
color4		#757974
color5		#906B67
color6		#71736F
color7		#5A5B57
color8		#8C8D87
color9		#C8CAC1
color10		#BEC1B8
color11		#B1B7AD
color12		#9CA19B
color13		#C08F8A
color14		#969994
color15		#DBDCD8
